@extends('layouts.index')
@section('content')
    @component($todoxxxx["rutacarp"].'tabsxxxx.index',['todoxxxx'=>$todoxxxx])
        @slot($todoxxxx['slotxxxx'])
            @switch($todoxxxx['accionxx'])
                @case('index')
                    @include('layouts.components.pestanias.indexgeneral')
                @break
                @case('Crear')
                    @include('layouts.components.pestanias.crear')
                @break
                @case('Editar')
                    @include('layouts.components.pestanias.editar')
                @break
                @case('Ver')
                    @include('layouts.components.pestanias.ver')
                @break
                @case('Destroy')
                    @include('layouts.components.pestanias.destroy')
                @break
                @case('Sin')
                    @include('layouts.components.pestanias.sinform')
                @break
            @endswitch
        @endslot
    @endcomponent
    @section('codigo')
        @if ($todoxxxx['accionxx']=='index')
            @include($todoxxxx["rutacarp"].$todoxxxx["carpetax"].'.js.tabla')
        @else
            @include($todoxxxx["rutacarp"].$todoxxxx["carpetax"].'.js.js')
        @endif
    @endsection
